loki:
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storageConfig:
    # storage_config:
    aws:
      bucketnames: loki
      endpoint: minio-dev.minio-dev.svc.cluster.local:9000
      access_key_id: rrz64Sr26EBnfTRyGpWz
      secret_access_key: 5iOgDd0dXLJwmCjUPMiEKjfOX7v0QerxiWHyqoK6
      insecure: true

#gateway:
#  ingress:
#    enabled: true
#    hosts:
#      - host: FIXME
#        paths:
#          - path: /
#            pathType: Prefix

ingester:
  replicas: 1
  replication_factor: 1
querier:
  replicas: 1
queryFrontend:
  replicas: 1
queryScheduler:
  replicas: 1
distributor:
  replicas: 1
compactor:
  enabled: true
  replicas: 1