loki:
  commonConfig:
    replication_factor: 3
  schemaConfig:
    configs:
    - from: "2024-01-01"
      store: tsdb
      index:
        prefix: loki_index_
        period: 24h
      object_store: s3
      schema: v13
  storage:
    type: 's3'
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      endpoint: minio-dev.minio-dev.svc.cluster.local:9000
      secretAccessKey: 5iOgDd0dXLJwmCjUPMiEKjfOX7v0QerxiWHyqoK6
      accessKeyId: rrz64Sr26EBnfTRyGpWz
      # s3ForcePathStyle: false
      insecure: true
singleBinary:
  replicas: 3