langfuse:
  salt:
    value: secureSalt
  nextauth:
    secret:
      value: "eb2ac57601b3949f975e48d8e5a05d36076f48212c37c5b027eb908ad9522d76" # `openssl rand -hex 32`で生成

postgresql:
  auth:
    # If you want to use `postgres` as the username, you need to provide postgresPassword instead of password.
    username: langfuse
    password: "langfuse"

clickhouse:
  auth:
    password: "langfuse"

redis:
  auth:
    password: "langfuse"

s3:
  auth:
    rootPassword: "langfuse"