apiVersion: ec2.aws.upbound.io/v1beta1
kind: Instance
metadata:
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    ami: ami-094dc5cf74289dfbc # Amazon Linux 2023 AMI
    instanceType: t2.small # kyvernoでt2.microのみ許可しているためデプロイできないことを確認
    region: ap-northeast-1
    tags:
      Name: lee-test-instance-from-crossplane
      owner: lee