# https://distribution.github.io/distribution/about/configuration/
# PersistentVolumeClaim for registry data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-storage-pvc
  namespace: registry
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi

---
# Registry Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
  labels:
    app: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
        revision: 20250701-1
    spec:
      containers:
      - name: registry
        image: registry:3
        ports:
        - containerPort: 5000
          name: http
        env:
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
        - name: registry-config
          mountPath: /etc/distribution
      volumes:
      - name: registry-storage
        persistentVolumeClaim:
          claimName: registry-storage-pvc
      - name: registry-config
        configMap:
          name: registry-config
      restartPolicy: Always
---
# Registry Service
apiVersion: v1
kind: Service
metadata:
  name: registry-service
  namespace: registry
  labels:
    app: registry
spec:
  selector:
    app: registry
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
    nodePort: 32272
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: registry
data:
  config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
        Access-Control-Allow-Origin: ['*']
        Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
        Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3