---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  # type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      # nodePort: 32100
  selector:
    app: grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:11.5.2
          imagePullPolicy: IfNotPresent
          env:
            - name: GF_SERVER_ROOT_URL
              value: https://grafana.dev-sutta.kinto-technologies.info/plat
            - name: GF_SERVER_DOMAIN
              value: grafana.dev-sutta.kinto-technologies.info
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              value: "true"
          #   - name: GF_DATABASE_TYPE
          #     valueFrom:
          #       secretKeyRef:
          #         name: rdsauth
          #         key: senaki-rds-engine
          #   - name: GF_DATABASE_HOST
          #     valueFrom:
          #       secretKeyRef:
          #         name: rdsauth
          #         key: senaki-rds-host
          #   - name: GF_DATABASE_NAME
          #     value: "grafana_sk"
          #   - name: GF_DATABASE_USER
          #     valueFrom:
          #       secretKeyRef:
          #         name: rdsauth
          #         key: senaki-rds-username
          #   - name: GF_DATABASE_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: rdsauth
          #         key: senaki-rds-password
          #   - name: GF_AUTH_SIGV4_AUTH_ENABLED
          #     value: "true"
          #   - name: AWS_DEFAULT_REGION
          #     value: "ap-northeast-1"
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          resources:
            requests:
              cpu: 100m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1000Mi