apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: lee-test
  namespace: flux-system
spec:
  interval: 30s
  url: https://github.com/AWS/Terraform/AWS/dev/tokyo
  ref:
    branch: main