apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: test-terraform
  namespace: flux-system
spec:
  interval: 1m
  approvePlan: auto
  path: ./AWS/Terraform/AWS/dev/tokyo
  sourceRef:
    kind: GitRepository
    name: lee-test
    namespace: flux-system