auth:
  postgresPassword: "postgres"
  database: "postgres"

primary:
  persistence:
    enabled: true
    size: 20Gi
    storageClass: local-path
  service:
    type: NodePort
    nodePorts:
      postgresql: 30432

readReplicas:
  replicaCount: 1

metrics:
  enabled: true