langfuse:
  encryptionKey:
    value: "464cd9aceec6e5cc96a7c29c8333b142691352bd99d3a9db492e406cb961b87f"
  salt:
    value: "d84133053e49394839525d4f8e8db5eb1d671bc674b568356f933d02c1cf8c7a"
  nextauth:
    secret:
      value: "BAhqqkbK4yEFIP0uIP1IeolzMuv8TciFroot"
    url: "http://192.168.0.146:30020" # WorkerNode01のIPアドレス
  web:
    service:
      type: NodePort
      nodePort: 30020

postgresql:
  deploy: false
  host: postgresql.postgresql.svc.cluster.local
  auth:
    database: postgres_langfuse
    username: postgres
    password: "postgres"

clickhouse:
  deploy: true
  persistence:
    enabled: true
    size: 10Gi
    storageClass: local-path
  auth:
    password: "clickhousepassword"

redis:
  deploy: true
  primary:
    persistence:
      enabled: true
      size: 10Gi
      storageClass: local-path
  auth:
    password: "redispassword"

s3:
  deploy: false
  bucket: langfuse