storage:
  trace:
    backend: s3
    s3:
      bucket: 'sk-tempo'
      endpoint: s3.ap-northeast-1.amazonaws.com
      insecure: false
multitenancyEnabled: true
gateway:
  enabled: true
  service:
    type: NodePort
    nodePort: 31090

# Specifies which trace protocols to accept by the gateway.
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false