storage:
  trace:
    backend: s3
    s3:
      bucket: 'sk-tempo'
      insecure: false
multitenancyEnabled: true
gateway:
  enabled: true

# Specifies which trace protocols to accept by the gateway.
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false