apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: monitoring
spec:
  replicas: 4
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
    spec:
      nodeSelector:
        karpenter.sh/nodepool: arm64-nodepool
        karpenter.sh/capacity-type: on-demand
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.37.2
        args:
        - query
        - --query.replica-label=prometheus_replica
        - --query.replica-label=receiver
        - --endpoint=thanos-store.monitoring.svc:10901
        - --endpoint=thanos-ingesting-receiver.monitoring.svc:10901
        - --query.tenant-header="THANOS-TENANT"
        - --query.enforce-tenancy
        - --query.auto-downsampling
        # - |
        #   --tracing.config=type: JAEGER
        #   config:
        #     service_name: "thanos-querier"
        #     sampler_type: const
        #     sampler_param: 1
        #     endpoint: "http://jaeger.monitoring.svc:14268/api/traces"
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query
  namespace: monitoring
  labels:
    app: thanos-query
spec:
  type: NodePort
  selector:
    app: thanos-query
  ports:
  - name: http
    port: 9090
    targetPort: 10902
    nodePort: 31500