apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-store
  template:
    metadata:
      labels:
        app: thanos-store
    spec:
      serviceAccountName: thanos-service-account
      nodeSelector:
        karpenter.sh/nodepool: arm64-nodepool
        karpenter.sh/capacity-type: on-demand
      containers:
      - name: thanos-store
        image: quay.io/thanos/thanos:v0.37.2
        args:
        - store
        - --data-dir=/tmp/thanos/store
        - --objstore.config-file=/etc/thanos/object-store.yaml
        # - |
        #   --tracing.config=type: JAEGER
        #   config:
        #     service_name: "thanos-ingesting-receiver"
        #     sampler_type: const
        #     sampler_param: 1
        #     endpoint: "http://jaeger.monitoring.svc:14268/api/traces"
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901
        volumeMounts:
        - name: object-store-config
          mountPath: /etc/thanos
      volumes:
      - name: object-store-config
        configMap:
          name: thanos-object-store-config
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-store
  namespace: monitoring
  labels:
    app: thanos-store
spec:
  type: NodePort
  selector:
    app: thanos-store
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
    nodePort: 31400