---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-compact-data-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-compactor
  namespace: monitoring
spec:
  replicas: 1 ## compactorは(bucketごとに)必ず1つのみ動いている必要がある
  selector:
    matchLabels:
      app: thanos-compactor
  template:
    metadata:
      labels:
        app: thanos-compactor
    spec:
      securityContext:
        fsGroup: 65534  # nobodyユーザーのgid
        runAsUser: 65534  # nobodyユーザーのuid
        runAsGroup: 65534
        runAsNonRoot: true
      containers:
      - name: thanos-compactor
        image: quay.io/thanos/thanos:v0.37.2
        args:
        - compact
        - --wait
        - --wait-interval=5m
        - --data-dir=/tmp/thanos/compact
        - --objstore.config-file=/etc/thanos/object-store.yaml
        - --retention.resolution-raw=30d
        - --retention.resolution-5m=180d
        - --retention.resolution-1h=365d
        # - |
        #   --tracing.config=type: JAEGER
        #   config:
        #     service_name: "thanos-compactor"
        #     sampler_type: const
        #     sampler_param: 1
        #     endpoint: "http://jaeger.metrics.svc:14268/api/traces"
        ports:
        - name: http
          containerPort: 10902
        volumeMounts:
        - name: thanos-compact-data
          mountPath: /tmp/thanos/compact
        - name: object-store-config
          mountPath: /etc/thanos
      volumes:
      - name: thanos-compact-data
        persistentVolumeClaim:
          claimName: thanos-compact-data-pvc
      - name: object-store-config
        configMap:
          name: thanos-object-store-config
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-compactor
  namespace: monitoring
  labels:
    app: thanos-compactor
spec:
  type: NodePort
  selector:
    app: thanos-compactor
  ports:
  - name: http
    port: 10902
    targetPort: http
    nodePort: 31300