apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query-frontend
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-query-frontend
  template:
    metadata:
      labels:
        app: thanos-query-frontend
    spec:
      nodeSelector:
        karpenter.sh/nodepool: arm64-nodepool
        karpenter.sh/capacity-type: on-demand
      containers:
      - name: thanos-query-frontend
        image: quay.io/thanos/thanos:v0.37.2
        args:
        - query-frontend
        - --http-address=0.0.0.0:9090
        - --query-frontend.downstream-url=http://thanos-query.monitoring.svc:9090
        - --query-range.split-interval=24h # default split interval
        - --query-range.request-downsampled
        # - |
        #   --tracing.config=type: JAEGER
        #   config:
        #     service_name: "thanos-query-frontend"
        #     sampler_type: const
        #     sampler_param: 1
        #     endpoint: "http://jaeger.monitoring.svc:14268/api/traces"
        ports:
        - name: http
          containerPort: 9090
        - name: metrics
          containerPort: 10902
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query-frontend
  namespace: monitoring
  labels:
    app: thanos-query-frontend
spec:
  type: NodePort
  selector:
    app: thanos-query-frontend
  ports:
  - name: http
    port: 9090
    targetPort: http
    nodePort: 31600
  - name: metrics
    port: 10902
    targetPort: metrics