---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: promtail
  namespace: monitoring
  labels:
    app: promtail
spec:
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
        version: 20240721-02
    spec:
      containers:
      - name: promtail
        image: grafana/promtail:3.1.0
        imagePullPolicy: IfNotPresent
        args:
          - '-config.file'
          - '/etc/promtail/promtail-config.yaml'
          - '-config.expand-env=true'
        command:
        - /usr/bin/promtail
        ports:
        - name: promtail
          containerPort: 9080
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: tmp
          mountPath: /tmp
        resources:
          requests:
            cpu: 150m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 500Mi
      volumes:
      - name: promtail-config
        configMap:
          name: promtail-config-configfile
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: tmp
        hostPath:
          path: /var/tmp
      hostNetwork: true
      hostPID: true
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config-configfile
  namespace: monitoring
data:
  promtail-config.yaml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
        - url: http://loki-gateway.monitoring.svc.cluster.local/loki/api/v1/push
          tenant_id: unk
          backoff_config:
            max_retries: 25
          external_labels:
            system: home-labs
            hostname: ${HOSTNAME}

    scrape_configs:
    - job_name: system
      static_configs:
      - targets:
          - localhost
        labels:
          job: dmesg
          __path__: /var/log/dmesg

    - job_name: kubernetes-pods
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: __host__
      # - source_labels: [__meta_kubernetes_namespace]
      #   regex: (default|kube-system|jenkins)
      #   action: drop
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod_name
      - source_labels: [__meta_kubernetes_pod_node_name]
        target_label: node_name
      - source_labels: [__meta_kubernetes_pod_uid, __meta_kubernetes_pod_container_name]
        separator: /
        replacement: /var/log/pods/*$1/*.log
        target_label: __path__

      # pipeline_stages:
      # - match:
      #     selector: '{pod_name=~"multi-tenant-loki-distributed-gateway-.*"}'
      #     stages:
      #     - regex:
      #         expression: "^.* (?P<status_code>[0-9]{3}) \"(?P<method>[A-Z].*?) (?P<uri>.*?) "
      #     - labels:
      #         status_code:
      #         method:
      #         uri:
      #     - metrics:
      #         loki_gateway_total:
      #           type: Counter
      #           config:
      #             match_all: true
      #             action: inc