apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rds-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: rdsauth
    creationPolicy: Owner
  data:
  - secretKey: senaki-rds-host
    remoteRef:
      key: senaki-rds-auth
      property: host
  - secretKey: senaki-rds-engine
    remoteRef:
      key: senaki-rds-auth
      property: engine
  - secretKey: senaki-rds-username
    remoteRef:
      key: senaki-rds-auth
      property: username
  - secretKey: senaki-rds-password
    remoteRef:
      key: senaki-rds-auth
      property: password