---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  selector:
    app: grafana
---
# nodeSelectorでworkernode01に配置
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        kubernetes.io/hostname: workernode01
      containers:
        - name: grafana
          image: grafana/grafana:12.1.1
          securityContext:
            runAsUser: 472
            runAsGroup: 472
            runAsNonRoot: true
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: grafana-storage
          hostPath:
            path: /mnt/grafana
            type: DirectoryOrCreate