# multitenancyEnabled: true
multitenancyEnabled: false
storage:
  trace:
    backend: s3
    s3:
      endpoint: minio-dev.minio-dev.svc.cluster.local:9000
      bucket: tempo-bucket
      access_key: minioadmin
      secret_key: minioadmin
      insecure: true
    empty_tenant_deletion_enabled: true
    empty_tenant_deletion_age: 12h # default: 12h
distributor:
  replicas: 1
ingester:
  replicas: 1
  config:
    replication_factor: 1
compactor:
  replicas: 1
  config:
    compaction:
      block_retention: 168h  # データを7日間（168時間）保存
querier:
  replicas: 1
queryFrontend:
  replicas: 1
  # 2025/06/27 なぜかquert-frontendだけ、affinityを無効にしてもAnti-Affinityに引っ掛かってPendingになるため、tolerationsを追加してMasterノードに配置
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"

# global:
#   clusterDomain: cluster.local
# metaMonitoring:
#   serviceMonitor:
#     enabled: true
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  jaeger:
    thriftHttp:
      enabled: true # 14268 port
tempo:
  structuredConfig:
    storage:
      trace:
        empty_tenant_deletion_enabled: true
        empty_tenant_deletion_age: 12h

metricsGenerator:
  enabled: true
  config:
    registry:
      collection_interval: 30s
      external_labels:
        source: tempo
      inject_tenant_id_as: tenant # Tenant IDが「tenant」ラベルに設定される
    storage:
      path: /var/tempo/wal
      remote_write:
        - url: http://cortex-tenant.monitoring.svc:8080/push # Cortex-tenant側で
          send_exemplars: true
      remote_write_add_org_id_header: true

overrides:
  defaults:
    metrics_generator:
      processors:
        - service-graphs
        - span-metrics
        - local-blocks # Grafana DrillDownが内部で使う TraceQL metrics クエリ（rate(), count_over_time() 等）には local-blocks が必須
