apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: deny-managed-admin-policy
spec:
  validationFailureAction: Enforce
  rules:
    - name: block-attach-admin-policy
      match:
        resources:
          kinds:
            - iam.aws.upbound.io/v1beta1/UserPolicyAttachment
      validate:
        message: "AdministratorAccessポリシーのアタッチは禁止されています。"
        deny:
          conditions:
            all:
              - key: "{{ request.object.spec.forProvider.policyArn }}"
                operator: AnyIn
                value:
                  - "arn:aws:iam::aws:policy/AdministratorAccess"