apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: metrics
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "list", "watch"]

  - apiGroups:
    - extensions
    resources:
    - ingresses
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources:
      - configmaps
      - nodes/proxy
    verbs: ["get"]
  
  - nonResourceURLs: 
      - /metrics
      - /metrics/cadvisor
      - /metrics/probes
    verbs: ["get"]
  
  - apiGroups: ["monitoring.coreos.com"]
    resources:
      - servicemonitors
      - podmonitors
      - prometheusrules
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-k8s
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: metrics