---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-compact
  namespace: monitoring
  labels:
    app: thanos
    component: compact
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos
      component: compact
  template:
    metadata:
      labels:
        app: thanos
        component: compact
    spec:
      nodeSelector:
        kubernetes.io/hostname: workernode02
      containers:
      - name: thanos-compact
        image: quay.io/thanos/thanos:v0.38.0
        args:
          - compact
          - --wait
          - --wait-interval=5m
          - --data-dir=/etc/thanos/compact
          - --objstore.config-file=/etc/thanos/object-storage.yaml
          - --retention.resolution-raw=30d
          - --retention.resolution-5m=90d
          - --retention.resolution-1h=180d
          - |
            --tracing.config=type: OTLP
            config:
              service_name: "thanos-compactor"
              sampler_type: const
              sampler_param: 1
              insecure: true
              client_type: http
              headers: { "X-Scope-OrgID": "homelab" }
              endpoint: "multi-tenant-tempo-distributor.monitoring.svc.cluster.local:4318"
        ports:
          - name: http
            containerPort: 10902
        volumeMounts:
        - name: thanos-compact-data
          mountPath: /etc/thanos/compact
        - name: object-store-config
          mountPath: /etc/thanos
      volumes:
      - name: thanos-compact-data
        persistentVolumeClaim:
          claimName: thanos-compact-data-pvc
      - name: object-store-config
        configMap:
          name: thanos-object-store-config
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-compact
  namespace: monitoring
  labels:
    app: thanos
    component: compact
spec:
  selector:
    app: thanos
    component: compact
  ports:
  - name: http
    port: 10902
    targetPort: 10902
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-compact-data-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi