---
apiVersion: v1
kind: ConfigMap
metadata:
  name: thanos-object-store-config
  namespace: monitoring
data:
  object-storage.yaml: |
    type: s3
    config:
      bucket: thanos
      endpoint: minio-dev.minio-dev.svc.cluster.local:9000
      access_key: rrz64Sr26EBnfTRyGpWz
      secret_key: 5iOgDd0dXLJwmCjUPMiEKjfOX7v0QerxiWHyqoK6
      insecure: true