apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query-frontend
  namespace: monitoring
spec:
  replicas: 2
  selector:
    matchLabels:
      app: thanos-query-frontend
  template:
    metadata:
      labels:
        app: thanos-query-frontend
    spec:
      containers:
      - name: thanos-query-frontend
        image: quay.io/thanos/thanos:v0.38.0
        args:
        - query-frontend
        - --http-address=0.0.0.0:9090
        - --query-frontend.downstream-url=http://thanos-querier.monitoring.svc:9090
        - --query-range.split-interval=24h # default split interval
        - --query-range.request-downsampled
        - |-
          --query-frontend.downstream-tripper-config=
          "max_idle_conns_per_host": 100
        - |
          --tracing.config=type: OTLP
          config:
            service_name: "thanos-query-frontend"
            sampler_type: const
            sampler_param: 1
            insecure: true
            client_type: http
            headers: { "X-Scope-OrgID": "homelab" }
            endpoint: "tempo-distributor.monitoring.svc.cluster.local:4318"
        ports:
        - name: http
          containerPort: 9090
        - name: metrics
          containerPort: 10902
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: thanos-query-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-query-frontend
  namespace: monitoring
  labels:
    app: thanos-query-frontend
spec:
  type: NodePort
  selector:
    app: thanos-query-frontend
  ports:
  - name: http
    port: 9090
    targetPort: http
    nodePort: 31600
  - name: metrics
    port: 10902
    targetPort: metrics