---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-store
  namespace: monitoring
  labels:
    app: thanos
    component: store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos
      component: store
  template:
    metadata:
      labels:
        app: thanos
        component: store
    spec:
      nodeSelector:
        kubernetes.io/hostname: workernode02
      containers:
      - name: thanos-store
        image: quay.io/thanos/thanos:v0.38.0
        args:
          - store
          - --data-dir=/etc/thanos/store
          - --objstore.config-file=/etc/thanos/object-storage.yaml
          - |
            --tracing.config=type: OTLP
            config:
              service_name: "thanos-store"
              sampler_type: const
              sampler_param: 1
              insecure: true
              client_type: http
              headers: { "X-Scope-OrgID": "homelab" }
              endpoint: "multi-tenant-tempo-distributor.monitoring.svc.cluster.local:4318"
        ports:
          - name: grpc
            containerPort: 10901
          - name: http
            containerPort: 10902
        volumeMounts:
          - name: thanos-store-config-vol
            mountPath: /etc/thanos
          - name: thanos-store-data-vol
            mountPath: /etc/thanos/store
      volumes:
        - name: thanos-store-config-vol
          configMap:
            name: thanos-object-store-config
        - name: thanos-store-data-vol
          persistentVolumeClaim:
            claimName: thanos-store-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: thanos-store
  namespace: monitoring
  labels:
    app: thanos
    component: store
spec:
  selector:
    app: thanos
    component: store
  ports:
  - name: grpc
    port: 10901
    targetPort: 10901
  - name: http
    port: 10902
    targetPort: 10902
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-store-data-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
