---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: external-secrets
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: vault-token
          key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-token
  namespace: external-secrets
data:
  token: aHZzLlNDUEk5R0RvZWg2Q1NpcnBrNldkZnJGbQ==
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: minio-credentials
  namespace: external-secrets
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: minio-access-key
      remoteRef:
        key: secret/minio/config
        property: accesskey
    - secretKey: minio-secret-key
      remoteRef:
        key: secret/minio/config
        property: secretkey