---
## ArgoCD
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nutslove/IaC.git'
    path: HomeLabs/k8s/ArgoCD
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
# Alloy
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alloy
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: alloy
    targetRevision: 1.1.2 # Helm Chartバージョン
    helm:
      releaseName: ""
      valueFiles:
      - $values/HomeLabs/k8s/Monitoring/Alloy/values.yaml
  - repoURL: 'https://github.com/nutslove/IaC.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
## Loki
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: loki
    targetRevision: 6.30.1 # Helm Chartバージョン
    helm:
      releaseName: ""
      valueFiles:
      - $values/HomeLabs/k8s/Monitoring/Loki/mircoservice-mode-values.yaml
  - repoURL: 'https://github.com/nutslove/IaC.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
## MinIO
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nutslove/IaC.git'
    path: HomeLabs/k8s/Utilities/MinIO
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio-dev
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
## LocalPathProvisioner
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-path-provisioner
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nutslove/IaC.git'
    path: HomeLabs/k8s/Utilities/LocalPathProvisioner
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: local-path-storage
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
## SecretManagement
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-management
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nutslove/IaC.git'
    path: HomeLabs/k8s/Utilities/SecretManagement
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
## Tempo
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://grafana.github.io/helm-charts'
    chart: tempo-distributed
    targetRevision: 1.42.3
    helm:
      releaseName: multi-tenant
      valueFiles:
      - $values/HomeLabs/k8s/Monitoring/Tempo/values.yaml
  - repoURL: 'https://github.com/nutslove/IaC.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
## PostgreSQL
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://charts.bitnami.com/bitnami'
    chart: postgresql
    targetRevision: 16.7.13
    helm:
      valueFiles:
      - $values/HomeLabs/k8s/Utilities/PostgreSQL/values.yaml
  - repoURL: 'https://github.com/nutslove/IaC.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: postgresql
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
## Langfuse
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: langfuse
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
  - repoURL: 'https://langfuse.github.io/langfuse-k8s'
    chart: langfuse
    targetRevision: 1.5.0
    helm:
      releaseName: langfuse
      valueFiles:
      - $values/HomeLabs/k8s/Monitoring/Langfuse/values.yaml
  - repoURL: 'https://github.com/nutslove/IaC.git'
    targetRevision: HEAD
    ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
## Common（NodeExporter, ProcessExporter, kube-state-metrics, etc.）
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: common
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nutslove/IaC.git'
    path: HomeLabs/k8s/Monitoring/Common
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
## Grafana
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nutslove/IaC.git'
    path: HomeLabs/k8s/Monitoring/Grafana
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
## Prometheus
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nutslove/IaC.git'
    path: HomeLabs/k8s/Monitoring/Prometheus
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
---
## Thanos
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanos
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nutslove/IaC.git'
    path: HomeLabs/k8s/Monitoring/Thanos
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
# ---
# ## Registry
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: registry
#   namespace: argocd
#   finalizers:
#   - resources-finalizer.argocd.argoproj.io
# spec:
#   project: default
#   source:
#     repoURL: 'https://github.com/nutslove/IaC.git'
#     path: HomeLabs/k8s/Utilities/Registry
#     targetRevision: HEAD
#   destination:
#     server: 'https://kubernetes.default.svc'
#     namespace: registry
#   syncPolicy:
#     automated: {}
#     syncOptions:
#     - CreateNamespace=true