---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  selector:
    matchLabels:
      app: opentelemetry
      component: otel-collector
  template:
    metadata:
      labels:
        app: opentelemetry
        component: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector:1.11.0
        args:
          - "--config=/conf/otel-collector-config.yaml"
        volumeMounts:
          - name: otel-collector-config-vol
            mountPath: /conf
      volumes:
        - name: otel-collector-config-vol
          configMap:
            name: otel-collector-conf
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: opentelemetry
    component: otel-collector
spec:
  ports:
  - name: otlp-grpc
    port: 4317
    protocol: TCP
    targetPort: 4317
  - name: otlp-http
    port: 4318
    protocol: TCP
    targetPort: 4318
  selector:
    app: opentelemetry
    component: otel-collector
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-conf
  labels:
    app: opentelemetry
    component: otel-collector-conf
data:
  otel-collector-config: |
    extensions:
      health_check:
      pprof:
        endpoint: 0.0.0.0:1777
      zpages:
        endpoint: 0.0.0.0:55679

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318
      prometheus:
        config:
          scrape_configs:
          - job_name: 'otel-collector'
            scrape_interval: 30s
            static_configs:
            - targets: ['localhost:8888']
          - job_name: 'node-exporter'
            scrape_interval: 30s
            static_configs:
            - targets: ['localhost:9100']
          - job_name: 'process-exporter'
            scrape_interval: 30s
            static_configs:
            - targets: ['localhost:9256']

    processors:
      batch:

    exporters:
      logging:
        verbosity: detailed
      otlp:
        #### Jaeger
        #endpoint: http://10.111.2.4:4317
        #tls:
          #insecure: true
      # prometheusremotewrite:
      #   endpoint: http://10.111.2.4:9009/api/v1/push
      #   tls:
      #     insecure: true
      #   external_labels:
      #     system: otel_demo

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, logging]

        metrics:
          receivers: [otlp, prometheus]
          processors: [batch]
          exporters: [otlp, prometheusremotewrite, logging]

        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp, logging]
      extensions: [health_check, pprof, zpages]